#!/usr/bin/env /opt/homebrew/bin/zsh

# inspired by:	https://github.com/Phantas0s/.dotfiles/blob/master/zsh/zshenv
# see also:	https://thevaluable.dev/zsh-install-configure-mouseless/

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

if [ "$(uname)" = "Darwin" ]; then
    export TERM='rxvt-color'
else
    export TERM='xterm'
fi
export DOTFILES="$HOME/.dotfiles"
export WORKSPACE="$HOME/workspace"

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$XDG_CONFIG_HOME/local/share
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache

export CONFIG="$XDG_CONFIG_HOME"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"		    # All other zsh config files will be loaded from this directory (.zprofile, .zshrc, etc)

# other software
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"    # Neovim config directory

# Man pages
export MANPAGER='nvim +Man!'
