#!/usr/bin/env zsh

zmodload zsh/zprof # Load zprof module, which provides profiling functions

source "$DOTFILES/zsh/prompt.zsh"

eval "$(/opt/homebrew/bin/brew shellenv)"

source "$DOTFILES/zsh/alias.zsh"
source "$DOTFILES/zsh/autocomplete.zsh"
source "$DOTFILES/zsh/bindings.zsh"
source "$DOTFILES/zsh/vim-mode.zsh"
source "$DOTFILES/zsh/plugins/zsh-syntax-highlighting.git/zsh-syntax-highlighting.zsh"

eval "$(gdircolors -b $DOTFILES/zsh/colors/nord.git/src/dir_colors)"

eval "$(pyenv init -)"
path+=(
    /Applications/Sublime\ Text.app/Contents/SharedSupport/bin
    /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin
    /Applications/Xcode.app/Contents/MacOS/
)
